### ISSUE TITLE
hm

### ISSUE THREAD

**Issue by Mach2401** [StarManiaKG/The-Story-of-Uncapped-Revengence-Discord-the-3rd#10]
![Screenshot 2023-04-17 12 57 09 AM](https://user-images.githubusercontent.com/129936070/232382476-aa9ffac0-c6c5-423b-88a6-2fcbb53b2fc9.png)

**Comment by StarManiaKG** [comment]
You'll need to compile it yourself from Discord's Github. While the link is provided in the README.md, [here's a link to it](https://github.com/discord/discord-rpc).
