### ISSUE TITLE
Entry point SDL_strtokr could not be located in DLL SDL2_mixer_ext.dll

### ISSUE THREAD

**Issue by DBaltian** [StarManiaKG/The-Story-of-Uncapped-Revengence-Discord-the-3rd#6]
I tried to launch the new version of TSoURDt3rd 2.3, but i gives me that error.

![image](https://user-images.githubusercontent.com/124071621/228237377-337e241d-fdba-405c-9e90-9bb55c6ead64.png)

**Comment by StarManiaKG** [comment]
Yeah, I've been made aware of this. I broke some DLL files, so I'm currently trying to fix this. Should take at least another half hour. Sorry about the inconvenience though.

**Comment by StarManiaKG** [comment]
This issue has been fixed. I'm going to close this now.
