### ISSUE TITLE
so.... this happens when i try to compile it on linux

### ISSUE THREAD

**Issue by Mach2401** [StarManiaKG/The-Story-of-Uncapped-Revengence-Discord-the-3rd#7]
![Screenshot 2023-04-12 1 50 03 PM](https://user-images.githubusercontent.com/129936070/231541977-f08518b5-a35e-4cea-9829-5726f7d4c0fc.png)

**Comment by coatlessali** [comment]
Can confirm, build fails. Not sure if dependencies are missing.

**Comment by StarManiaKG** [comment]
Thanks for letting me know about this, but I actually just fixed it a while ago. Check the ```unstablemain``` branch.
