### ISSUE TITLE
Old-school pause menu option not working

### ISSUE THREAD

**Issue by PinkyPis** [StarManiaKG/The-Story-of-Uncapped-Revengence-Discord-the-3rd#8]
When I ticked on the old-school pause option, it did nothing.

**Comment by StarManiaKG** [comment]
That's weird. It works perfectly fine for me. Did you see a graphic change on your screen when you ticked the option on and then paused the game, though? If you did, that means it did something.

**Comment by StarManiaKG** [comment]
Closing this Issue Because it's Been Two Weeks.
