### ISSUE TITLE
discord options where?

### ISSUE THREAD

**Issue by Mach2401** [StarManiaKG/The-Story-of-Uncapped-Revengence-Discord-the-3rd#9]
![Screenshot 2023-04-15 10 50 27 PM](https://user-images.githubusercontent.com/129936070/232263666-b5e8927a-6be4-473f-8c1d-99ca0548d9b6.png)

**Comment by StarManiaKG** [comment]
You need to compile with the ```HAVE_DISCORDRPC=1``` flag.
